greeting:
  message: "hello"
mp:
  messaging:
    outgoing:
      outgoingTopicNameWillComeFromConfig:
        topic: "quotes"
      words-out:
        topic: "words"
    incoming:
      movies-from-kafka:
        topic: "cinema"
        connector: "smallrye-kafka"
        enable:
          auto:
            commit: false
        value:
          deserializer: com.guptaji.deserializations.CinemaDeserializer
        auto:
          offset:
            reset: "earliest"
      incomingTopicNameWillComeFromConfig:
        topic: "quote-data-request"
        auto:
          offset:
            reset: "earliest"
      words-in:
        auto:
          offset:
            reset: "earliest"
        topic: "words"

quarkus:
  http:
    port: 8087
